version: 2.1

jobs:
  Testing-Job:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run:
          name: "Install NodeJS"
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
            chmod +x nodesource_setup.sh
            bash nodesource_setup.sh
            apt install -y nodejs
      - run:
          name: "Install Postman CLI & Newman"
          command: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
            npm install newman newman-reporter-htmlextra
      - run:
          name: "Login to Postman"
          command: postman login --with-api-key $POSTMAN_API_KEY
      - run:
          name: "Running Test - Postman CLI"
          command: postman collection run --environment 27807400-c2f6805d-031c-415f-afc1-6227120f5348 27807400-54ac2c5b-8261-4a2c-8bc4-8314a0004b3c
      - run:
          name: "Running Test - Newman"
          command: newman run --environment ./environment/HTTP-Sample-Env.postman_environment.json ./collection/HTTP-Sample.postman_collection.json --reporters htmlextra --reporter-htmlextra-export ./reports/report.html
      - run:
          name: "Wrapping Test Result"
          command: tar -cvf artifact.tar ./reports/
      - store_artifacts:
          path: artifact.tar

workflows:
  Testing-Workflow:
    jobs:
      - Testing-Job
